---
- hosts: "{{ servers }}"
  become: true
  tasks:
  - name: install apache
    package:
      name: httpd
      state: present
    tags: install
  - name: iniciar httpd y enabled
    service:
      name: httpd
      state: started
      enabled: yes
    tags: install
  - name: creamos la pagina de inicio
    file:
      path: /var/www/html/index.html
      state: touch
    tags: config
  - name: añadimos contenido al fichero
    copy:
      content: "Hallo my friends"
      dest: /var/www/html/index.html
    tags: config
  - name: desinstalar apache
    package: 
      name: httpd
      state: absent
    tags: [never, uninstall]