---
- hosts: "{{ servers }}"
  become: true
  tasks:
  - name: conectar al apache
    uri:
      url: "http://{{ servers }}"
    ignore_errors: true
  - name: crear directorio
    file:
      name: /var/tmp/test
      state: directory